## 利用GitHub Actions每天定时给微信群推送消息 ##

name: wxPush

# 两种触发方式：一、push代码，二、每天国际标准时间23点（北京时间+8即早上7点）运行
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *' # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule

# on:
#   schedule:
#     - cron: '*/5 * * * *' # 每5分钟一次，测试用

jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v2
       # 使用 node:10
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: .gitignore
      # 拉取远程仓库代码
      - name: git pull origin
        run: |
          git config pull.rebase false
          git config --global user.email "skdream@126.com"
          git config --global user.name "skdream"
          git pull  https://github.com/fe-cool/news.git main --allow-unrelated-histories

          # git rebase --continue

        # npm install
      - name: npm install
        run: npm install
        env:
          CI: true
      - name: 'Run wxPush' # 步骤二，执行sh命令文件
        env:	#添加环境变量
          SKEY: ${{ secrets.SKEY }}
        run: node ./wxPush.js # 运行目录是仓库根目录